### ISSUE TITLE
Bug report by javascript side load

### ISSUE THREAD

**Issue by zandercodes** [LukeTowers/oc-easyspa-plugin#9]
Sideload via Ajax another pages in a container and click on a element in This container reload the complete page. Why?

**Comment by LukeTowers** [comment]
I have no idea what you're talking about. Please provide full replication instructions.

**Comment by zandercodes** [comment]
I have make a little Video for the bug.
YouTube: https://youtu.be/Gpu-C4-9JAs

**Comment by LukeTowers** [comment]
Still have no idea, all I saw was someone clicking on a bunch of elements and a bunch of loading indicators appear.

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

As a side note, this is not a free plugin, see https://github.com/LukeTowers/oc-easyspa-plugin/blob/master/LICENSE and https://octobercms.com/plugin/luketowers-easyspa.

If you have purchased this plugin from the OctoberCMS marketplace please provide your username so that I can verify that you have purchased it and will be more interested in helping you out.
